### ISSUE TITLE
Implement balance snapshotting to Disk

### ISSUE THREAD

**Issue by haerdib** [Polkadex-Substrate/polkadexTEE-worker#173]
Implement balance snapshotting to permanent storage on disk

check out https://github.com/Polkadex-Substrate/polkadexTEE-worker/blob/develop/worker/src/polkadex_db.rs for an example (or maybe extend current version?)

**Comment by haerdib** [comment]
This issue is an extension of issue #4 .

@Gauthamastro , @brenzi 
Is the original idea e.g. : 
- no confidentiality requirements: store as plaintext,
- time interval based
- commit snapshots to chain with an `ocex::snapshot` extrinsic signed by enclave signing key

still valid as such?

EDIT: Still valid (see hidden comment from brenzi. Was marked as off topic, but actually moved to issue #177)

**Comment by brenzi** [comment]
The above is still valid IMO

Regarding the state that needs snapshotting: We only need to restore things that can't be synced from the chain again
The proxy set doesn't strictly need snapshotting but it won't hurt (debug only. just don't restore, because you would overwrite chain-synced state)

the orderbook mirror, the balances, need snapshotting. The order cache for the OpenFinex API maybe not because these would be in limbo anyway if the ws connection breaks

**Comment by haerdib** [comment]
@Gauthamastro 
In this issue I've written 
> commit snapshots to chain with an ocex::snapshot extrinsic signed by enclave signing key,

however, as we're snapshotting CID to the chain, is this still valid as such?
If not, this issue can be closed with #238

**Comment by Gauthamastro** [comment]
> @Gauthamastro 
> In this issue I've written 
> > commit snapshots to chain with an ocex::snapshot extrinsic signed by enclave signing key,
> 
> however, as we're snapshotting CID to the chain, is this still valid as such?
> If not, this issue can be closed with #238

The idea is to send IPFS CIDs to OCEX pallet which will then picked up by off chain workers and pin those CIDs after verification.

**Comment by haerdib** [comment]
Cosed with #238, the sending of CIDs will be implemented in #241
