### ISSUE TITLE
Black Box integration testing

### ISSUE THREAD

**Issue by pavankanteti** [Polkadex-Substrate/polkadexTEE-worker#202]
Includes CI integration

**Comment by zktony** [comment]
Black Box integration testing with OpenFinex server using Python Script.

**Comment by haerdib** [comment]
We have the following scripts already:
-[happy_flow](https://github.com/Polkadex-Substrate/polkadexTEE-worker/blob/develop/client/polkadex_demo_happy_flow.py)
-[gateway rejects order because of too few balances](https://github.com/Polkadex-Substrate/polkadexTEE-worker/blob/develop/client/polkadex_demo_scenario_two.py)
-[gateway rejects withdraw because too few balances](https://github.com/Polkadex-Substrate/polkadexTEE-worker/blob/develop/client/polkadex_demo_scenario_three.py)

What we should test additionally:
- Alice successfully creates an order (without a matching order from bob!) and is able to cancel it. Only then bob issues a matching order, but it does not get matches in xx seconds. Only when alice creastes a new order, they get a match
- registered proxy can create and cancel orders , but not registered proxies can not do that. But, ofc, only for its righteous main accounts otherwise order creation/cancel gets rejected as well.
- proxies, also registered ones, can not: withdraw or deposit balances
- I guess some polkadex orderbook handling tests would make sense (does the right amount of money get reservered after order creation? Does the right amaount of money get traded? I think you have the better idea what's necessary there.. and if its necessary for black box testing)

**Comment by haerdib** [comment]
The OrderUUID can not be returned directly to the client because openfinex answer is received by a separate thread. But the orderUUID can still be returned to the user by "storing" the client waiting for the oderUUID in a cache in the worker, and when openfinex returns the UUID, the enclave will send an ocall to this cache containing the orderUUID (and the client ID). The cache will then forward the order UUID to the client.. afterwards the cache will remove the client from the waiting lsit.

The cache - code is already there, we jsut need to adapt it to fit our use case:
- set `do_watch` from `false` to `true` [here](https://github.com/Polkadex-Substrate/polkadexTEE-worker/blob/develop/enclave/src/rpc/rpc_place_order.rs#L77)
- adapt the [server client hashing](https://github.com/Polkadex-Substrate/polkadexTEE-worker/blob/develop/worker/src/enclave/worker_api_direct_server.rs#L180-L199) to our use case: Whenever a `do_watch = true` is returned, we create a new ClientEntry in the watch_list, like it is done [here](https://github.com/Polkadex-Substrate/polkadexTEE-worker/blob/develop/worker/src/enclave/worker_api_direct_server.rs#L198). The hash needs to be something like a ClientUUID, which the enclave knows / can retrieve when the openfinex server answers with the order UUID. In our case that could be the [request id](https://github.com/Polkadex-Substrate/polkadexTEE-worker/blob/develop/enclave/src/openfinex/openfinex_api.rs#L51).
- To receive this answer, the ws connection needs to be kept open by the client code (be it rust or react). It will receive two answers: One the one we already have implemented: Ok(()) or maybe Ok(request id). And shortly afterwards an Ok(OrderUuid) or just an OrderUUID. Whatever works best.
- Additionally, we will need the implement the client call return logic within the enclave: upon receiving the order UUID, it will send an ocall to the worker, containing the ClientUUID (reuqest id?) and the order UUID. An example is  implemented [here (worker side)](https://github.com/Polkadex-Substrate/polkadexTEE-worker/blob/develop/worker/src/enclave/worker_api_direct_server.rs#L267-L300) and [here (enclave side)](https://github.com/Polkadex-Substrate/polkadexTEE-worker/blob/develop/enclave/src/rpc/worker_api_direct.rs#L252-L276)

**Comment by pavankanteti** [comment]
EOD 8/4/21
