### ISSUE TITLE
Getting 'InvalidFinalityProof' error, when PolkadexTEE worker is ran little longer 

### ISSUE THREAD

**Issue by zktony** [Polkadex-Substrate/polkadexTEE-worker#229]
When PolkadexTEE worker is ran little longer, then it starts giving these logs continuously :-
```
[2021-08-06T04:58:22Z ERROR substratee_worker_enclave] Block verification failed. Error : InvalidFinalityProof
[2021-08-06T04:58:22Z ERROR substratee_worker] SGX_ERROR_UNEXPECTED
Chain Relay is synced until block: 1023
Last finalized block number: 1845

[2021-08-06T04:58:25Z ERROR substratee_worker_enclave] Block verification failed. Error : InvalidFinalityProof
[2021-08-06T04:58:25Z ERROR substratee_worker] SGX_ERROR_UNEXPECTED
Chain Relay is synced until block: 1023
Last finalized block number: 1846
```

**Comment by zktony** [comment]
Verify if jwt is with a right role and level

**Comment by haerdib** [comment]
@zktony I've ran the node & worker a little bit longer and I am over block 1100 now. Could you provide some more information in which environment you have run the worker and node?
I will try again tomorrow and see if I hit a limit somewhen.

UPDATE: I got the same error at Block 1535

**Comment by haerdib** [comment]
So the issue it the justifiaction. Up to the failure, no justifications has been sent from the node.
![grafik](https://user-images.githubusercontent.com/73821294/129369924-2bf83948-48fe-4a4f-b89c-667a5e8fe793.png)

If justification is none, then the test will be skipped, here:  https://github.com/integritee-network/worker/blob/99c4b3aadaf0c320819752cbd5d12a81ec39fabb/enclave/chain_relay/src/lib.rs#L258
but if it is not none, it will be checked, and this seems to fail. I'll try to find out why.

**Comment by haerdib** [comment]
So, my investigations brought out the following: the current Polkadex node is issuing grandpa justifications every 512 blocks (https://github.com/Polkadex-Substrate/Polkadex/blob/main/node/src/service.rs#L404). Hence the errors at block ~1000 or ~1500. 
Additionally: A node build runs deterministically, hence pruging & restarting the chain will not change the output. 

To test if the enclave justification / node justification have a gernal mismatch, I set the justification period to 1, and up till now it's running fine (380 blocks imported, 380 justifications verified). So that's not the case. 

I'm suggesting to let this problem be solved upstrea,, as it's a general substratee problem: https://github.com/integritee-network/worker/issues/353

**Comment by haerdib** [comment]
Issue has been solved upstream with: https://github.com/integritee-network/worker/pull/365.

So, when rebasing our current worker with the integritee worker (#256), this issue should be solved.

**Comment by zktony** [comment]
Awesome

**Comment by zktony** [comment]
@haerdib if this can be solved without upgradation then it would be great. 
CC @simonsso @pavankanteti
