### ISSUE TITLE
Substrate API Client is returning Metadata(MapValueTypeError)

### ISSUE THREAD

**Issue by Gauthamastro** [Polkadex-Substrate/polkadexTEE-worker#42]
It is returning Metadata(MapValueTypeError) inside the worker when trying to get the LinkedAccount and proof, but the same code is working fine when implemented as a standalone application.

**Comment by brenzi** [comment]
happens during
https://github.com/Polkadex-Substrate/polkadexTEE-worker/blob/87de5f290f5d56ed1c56d008b90a68d1e94de73b/worker/src/main.rs#L532

**Comment by brenzi** [comment]
reproduced:

node runs `develop` branch
worker runs `develop` branch

```
*** Starting substraTEE-worker
Advertising worker api at ws://127.0.0.1:2000
Encointer Worker v0.8.0
*** Starting enclave in development mode
MRENCLAVE=AJ1qiNGmhJJkyk8gdaiZjNTYjB77WmujUCNKSkYKsxvZ
MU-RA server listening on ws://127.0.0.1:3443
rpc worker server listening on ws://127.0.0.1:2000
Successfully initialised top pool
[+] bootstrap funding Enclave form Alice's funds
    [Enclave] Create attestation report successful
[>] Register the enclave (send the extrinsic)
[<] Extrinsic got finalized. Hash: Some(0xb54aee82dc73534055101db76c38c45ab7e4484f1cad3ad8c76a28d04b299ed5)

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Metadata(MapValueTypeError)', worker/src/polkadex.rs:44:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

```

**Comment by brenzi** [comment]
I'm pretty sure this is caused by a type mismatch:

The runtime defines:
https://github.com/Polkadex-Substrate/Polkadex/blob/dab5521a7ae485af4fbce015a3d38c39bdb9e622/pallets/ocex/src/lib.rs#L42-L46

The worker polkadex-primitives define:
https://github.com/Polkadex-Substrate/polkadexTEE-worker/blob/d2291c323ae5c7c716eeada60785fb6b8555e4a0/polkadex-primitives/src/lib.rs#L15-L20

The order matters! Please adjust one of the two definitions to reflect exactly the same type. My preference would actually be to depend on polkadex-primitives even in the pallet. To reduce redundant code.

**Comment by brenzi** [comment]
@Gauthamastro ^^^

**Comment by Gauthamastro** [comment]
Yes, this works
