### ISSUE TITLE
Remove redundant LinkedAccount

### ISSUE THREAD

**Issue by Gauthamastro** [Polkadex-Substrate/polkadexTEE-worker#54]
LinkedAccount is defined in OCEX Pallet and in polkadex-sgx-primitives, define it in polkadex-sgx-primitives and import it in ocex pallet

**Comment by arrudagates** [comment]
polkadex-sgx-primitives is using the sp_core dependency with full crypto due to this function
https://github.com/Polkadex-Substrate/polkadexTEE-worker/blob/develop/polkadex-primitives/src/accounts.rs#L24-L28
since the node cannot have a dependency with full crypto, that function is being moved to substratee_worker_primitives.

**Comment by arrudagates** [comment]
Everything needed for this issue in this repo has been done, LinkedAccount struct has implementations needed to work in the OCEX pallet in node, so an issue should be opened there about it and this one should be closed.
